"""
ftp_server.py — FTP server for CloudinatorFTP
----------------------------------------------
Runs a pyftpdlib FTP server on FTP_PORT (default 2121) in a background
daemon thread, exposing ROOT_DIR over FTP.

TLS (FTPS — explicit AUTH TLS) is used automatically when the `pyOpenSSL`
package is installed and FTP_TLS_ENABLED is not disabled in config.py.
It reuses the SAME cert as WebDAV HTTPS (db/webdav.crt, generated by
ssl_cert.py) — a proper CA cert, not a throwaway self-signed one — so
importing it once as a Trusted Root (see ssl_cert.py's docstring) covers
both WebDAV HTTPS *and* FTPS on every client. When TLS is active, the
control channel is upgraded via `AUTH TLS` (client issues it, same port —
no separate implicit-FTPS 990 port), and the data channel is TLS-required
by default (see FTP_TLS_REQUIRE_DATA below).

⚠️  If TLS is unavailable (pyOpenSSL missing, or FTP_TLS_ENABLED=False),
    this falls back to PLAINTEXT FTP — use only on trusted local networks
    in that case. For internet-facing use, prefer SFTP, WebDAV, or FTPS.

NOTE: FTP cannot be used as a native OS drive letter/mount.
      It is useful for: WinSCP, FileZilla, legacy FTP clients.

Client usage:
  WinSCP    → Protocol: FTP  Encryption: Explicit TLS  Host: HOST  Port: 2121
  FileZilla → Protocol: FTP  Encryption: Require explicit FTP over TLS
  CLI       → ftp HOST 2121  (then: AUTH TLS, USER <username>, PASS <password>)

Roles (same as Flask):
  readwrite → full FTP: list, download, upload, delete, rename, mkdir …
  readonly  → list + download only (elr permissions)

Authentication is against the CloudinatorFTP database (same credentials).
The home directory for all users is ROOT_DIR.  Users are chrooted to it.
"""

import logging
import threading
import logging_setup
from app import get_local_ip

LOCAL_IP = get_local_ip()

# Was logging.getLogger(__name__), then never actually called anywhere in
# this file — a dead logger. Now a child of logging_setup's shared
# "cloudinatorftp" logger (same fix as protocol_manager.py's _pm_logger
# and sftp_server.py's log), and actually used below for audit logging.
# NOTE: this is separate from pyftpdlib's own internal 'pyftpdlib' logger
# (used for its low-level protocol trace) — that one is intentionally
# left alone here; AUDIT lines below are written explicitly through this
# logger instead of relying on pyftpdlib's internal logging reaching the
# app's unified log file, which it doesn't by default.
log = logging_setup.get_logger("ftp")

# pyftpdlib permission strings
# e = change dir, l = list, r = download
# a = append, d = delete, f = rename, m = mkdir, w = upload, M = chmod, T = mtime
_PERMS_READWRITE = "elradfmwMT"
_PERMS_READONLY = "elr"

_server = None
_thread: threading.Thread | None = None

_TLS_ACTIVE = False  # set once _make_server() decides; used by start()'s banner


# ── TLS support ────────────────────────────────────────────────────────────


def _tls_available() -> bool:
    """True if pyftpdlib's TLS handler + pyOpenSSL are importable."""
    try:
        from pyftpdlib.handlers import TLS_FTPHandler  # noqa
        import OpenSSL  # noqa
    except ImportError:
        return False
    return True


def _resolve_tls_cert_paths():
    """
    Returns (certfile, keyfile) for FTPS, reusing the SAME CA-importable
    cert as WebDAV HTTPS (ssl_cert.py → db/webdav.crt + webdav.key).

    This is intentional, not just convenient: it's a proper CA cert (not a
    throwaway self-signed one), and importing it once as a Trusted Root
    (see ssl_cert.py's docstring) covers WebDAV HTTPS *and* FTPS on every
    client — no second cert to generate, distribute, or re-trust.
    """
    from config import DB_DIR
    from ssl_cert import get_cert_paths

    return get_cert_paths(DB_DIR)


# ── Custom authorizer ─────────────────────────────────────────────────────


def _make_authorizer():
    from pyftpdlib.authorizers import AuthenticationFailed

    class CloudinatorAuthorizer:
        """
        FTP authorizer backed by the CloudinatorFTP database.

        Does NOT inherit from DummyAuthorizer because on Windows,
        DummyAuthorizer.impersonate_user() calls win32security.LogonUser()
        which tries to log in as a real Windows OS account.  Since our users
        exist only in the SQLite database (not as Windows users), that call
        raises AuthorizerError and blocks all file operations after login.

        By implementing the interface directly with no-op impersonate methods
        we use only our own DB credentials — the same ones as the web UI.
        """

        # ── Called during USER command (before password) ───────────────────

        def has_user(self, username: str) -> bool:
            from database import db

            return db.user_exists(username)

        # ── Called during PASS command ─────────────────────────────────────

        def validate_authentication(self, username: str, password: str, handler):
            from database import db

            if not db.check_login(username, password):
                raise AuthenticationFailed("Invalid username or password.")
            db.update_last_login(username)

        # ── Called after successful auth ───────────────────────────────────

        def get_home_dir(self, username: str) -> str:
            from config import ROOT_DIR

            return ROOT_DIR

        # ── Called before every file operation ────────────────────────────

        def has_perm(self, username: str, perm: str, path=None) -> bool:
            from database import db

            role = db.get_role(username) or "readonly"
            allowed = _PERMS_READWRITE if role == "readwrite" else _PERMS_READONLY
            return perm in allowed

        def get_perms(self, username: str) -> str:
            from database import db

            role = db.get_role(username) or "readonly"
            return _PERMS_READWRITE if role == "readwrite" else _PERMS_READONLY

        # ── Login / quit banners ───────────────────────────────────────────

        def get_msg_login(self, username: str) -> str:
            from database import db

            role = db.get_role(username) or "readonly"
            access = "read-write" if role == "readwrite" else "read-only"
            return f"Welcome to CloudinatorFTP. Logged in as {username} ({access})."

        def get_msg_quit(self, username: str) -> str:
            return "Goodbye!"

        # ── OS impersonation — intentional no-ops ─────────────────────────
        # DummyAuthorizer tries to impersonate real OS accounts here.
        # Our users are DB-only, not OS accounts, so we skip impersonation.

        def impersonate_user(self, username: str, password: str):
            pass

        def terminate_impersonation(self, username: str):
            pass

    return CloudinatorAuthorizer()


# ── Build FTP server ──────────────────────────────────────────────────────


def _make_server(port: int):
    from pyftpdlib.servers import FTPServer

    global _TLS_ACTIVE

    try:
        from config import FTP_TLS_ENABLED
    except ImportError:
        FTP_TLS_ENABLED = True  # default on when the dep is present

    use_tls = FTP_TLS_ENABLED and _tls_available()

    certfile = keyfile = None
    if use_tls:
        from pyftpdlib.handlers import TLS_FTPHandler as BaseHandler

        try:
            certfile, keyfile = _resolve_tls_cert_paths()
        except Exception as e:
            print(
                f"⚠️  FTP: could not resolve/generate the shared TLS cert ({e}) — "
                "falling back to PLAINTEXT FTP."
            )
            use_tls = False
            from pyftpdlib.handlers import FTPHandler as BaseHandler
    else:
        from pyftpdlib.handlers import FTPHandler as BaseHandler

        if FTP_TLS_ENABLED and not _tls_available():
            print(
                "⚠️  FTP: FTP_TLS_ENABLED is set but pyOpenSSL isn't installed — "
                "falling back to PLAINTEXT FTP."
            )
            print("   Install it: pip install pyOpenSSL")

    # We subclass the handler so each instance gets its own authorizer.
    # (Assigning to the class directly affects all instances globally.)
    class CloudinatorFTPHandler(BaseHandler):
        authorizer = _make_authorizer()
        banner = "CloudinatorFTP Server ready."
        passive_ports = range(60000, 60100)
        # Disable masquerade by default; set to your public IP if behind NAT:
        #   masquerade_address = "1.2.3.4"
        masquerade_address = None
        max_login_attempts = 5
        timeout = 300  # idle disconnect after 5 minutes

        # ── Audit logging (new) ─────────────────────────────────────────
        # pyftpdlib exposes on_login/on_login_failed/on_file_sent/
        # on_file_received as ready-made callbacks — used directly below.
        # Delete/rename/mkdir/rmdir have no equivalent "on_X" callback in
        # this library, so those four are wrapped by calling the base
        # class's ftp_DELE/ftp_RMD/ftp_MKD/ftp_RNTO first (unchanged
        # behavior, including its own error responses) and then checking
        # self._last_response — set by every pyftpdlib respond() call —
        # to tell success ("250"/"257") from failure ("550") before
        # writing the audit line. Mirrors the same user+action+path+ip
        # shape used in sftp_server.py's _audit() and app.py's request
        # logger, so all three protocols' logs are greppable the same way.

        def on_login(self, username):
            perms = self.authorizer.get_perms(username)
            role = "readwrite" if "d" in perms else "readonly"
            log.info(
                "FTP AUDIT: user=%r action=login role=%s ip=%s tls=%s",
                username,
                role,
                self.remote_ip,
                _TLS_ACTIVE,
            )

        def on_login_failed(self, username, password):
            # Previously silent — a failed FTP login (bad password, or a
            # non-existent username) produced no log line at all.
            log.warning(
                "FTP AUDIT: user=%r action=login_failed ip=%s", username, self.remote_ip
            )

        def on_file_sent(self, file):
            log.info(
                "FTP AUDIT: user=%r action=download path=%r ip=%s",
                self.username,
                file,
                self.remote_ip,
            )

        def on_file_received(self, file):
            log.info(
                "FTP AUDIT: user=%r action=upload path=%r ip=%s",
                self.username,
                file,
                self.remote_ip,
            )

        def ftp_DELE(self, path):
            result = super().ftp_DELE(path)
            if self._last_response.startswith("250"):
                log.info(
                    "FTP AUDIT: user=%r action=delete path=%r ip=%s",
                    self.username,
                    path,
                    self.remote_ip,
                )
            return result

        def ftp_RMD(self, path):
            result = super().ftp_RMD(path)
            if self._last_response.startswith("250"):
                log.info(
                    "FTP AUDIT: user=%r action=rmdir path=%r ip=%s",
                    self.username,
                    path,
                    self.remote_ip,
                )
            return result

        def ftp_MKD(self, path):
            result = super().ftp_MKD(path)
            if self._last_response.startswith("257"):
                log.info(
                    "FTP AUDIT: user=%r action=mkdir path=%r ip=%s",
                    self.username,
                    path,
                    self.remote_ip,
                )
            return result

        def ftp_RNTO(self, path):
            # Capture the source path before super() clears self._rnfr.
            src = self._rnfr
            result = super().ftp_RNTO(path)
            if self._last_response.startswith("250"):
                log.info(
                    "FTP AUDIT: user=%r action=rename path=%r -> %r ip=%s",
                    self.username,
                    src,
                    path,
                    self.remote_ip,
                )
            return result

    if use_tls:
        CloudinatorFTPHandler.certfile = certfile
        CloudinatorFTPHandler.keyfile = keyfile
        # Require TLS on the control channel (creds must be encrypted).
        CloudinatorFTPHandler.tls_control_required = True
        # Require TLS on the data channel too (uploads/downloads/listings),
        # unless explicitly relaxed in config.py for a legacy client.
        try:
            from config import FTP_TLS_REQUIRE_DATA
        except ImportError:
            FTP_TLS_REQUIRE_DATA = True
        CloudinatorFTPHandler.tls_data_required = FTP_TLS_REQUIRE_DATA

    _TLS_ACTIVE = use_tls

    server = FTPServer(("0.0.0.0", port), CloudinatorFTPHandler)
    server.max_cons = 256
    server.max_cons_per_ip = 10
    return server


# ── Public API ────────────────────────────────────────────────────────────


def start(port: int = None) -> bool:
    """
    Start the FTP server in a background daemon thread.
    Returns True on success, False if pyftpdlib is not installed.
    """
    global _server, _thread

    try:
        from config import FTP_ENABLED, FTP_PORT
    except ImportError:
        FTP_ENABLED, FTP_PORT = True, 2121

    if not FTP_ENABLED:
        return False

    port = port or FTP_PORT

    try:
        import pyftpdlib  # noqa — verify available
    except ImportError:
        print("⚠️  FTP not started: 'pyftpdlib' is not installed.")
        print("   Install it: pip install pyftpdlib")
        return False

    try:
        _server = _make_server(port)
    except OSError as e:
        print(f"❌ FTP: cannot bind to port {port}: {e}")
        return False
    except Exception as e:
        print(f"❌ FTP server build failed: {e}")
        return False

    _thread = threading.Thread(
        target=_server.serve_forever,
        name="ftp-server",
        daemon=True,
    )
    _thread.start()

    print(f"📁 FTP:     ftp://{LOCAL_IP}:{port}/")
    if _TLS_ACTIVE:
        print(
            f"   🔒 FTPS active (explicit AUTH TLS) — control + data channels encrypted"
        )
        print(
            f"   WinSCP → Protocol: FTP  Encryption: Explicit TLS  Host: {LOCAL_IP}  Port: {port}"
        )
    else:
        print(f"   ⚠️  FTP sends credentials in plaintext — local network only")
        print(f"   WinSCP → Protocol: FTP  Host: {LOCAL_IP}  Port: {port}")
    print(f"   Passive data ports: 60000–60100 (open these in your firewall)")
    return True


def stop():
    """Shut down the FTP server (best-effort)."""
    global _server
    if _server:
        try:
            _server.close_all()
        except Exception:
            pass
        _server = None
