#!/usr/bin/env python3
"""
Single source of truth for the app.py split: which phase moves what, where.
Generated 2026-10-06 from the pristine app.py (CLAUDE.md 4.67) by AST analysis, then
edited by hand where noted. If a symbol is re-assigned during a phase, edit it HERE
(and in the CLAUDE.md map) in the same commit - the phase tests read this file.
"""

# Names that other modules import from `app` and that must stay importable from app.py.
# sftp_server.py / ftp_server.py / smb_server.py do `from app import get_local_ip`
# (per app.py's own comment). Run `grep -rn "from app import\|import app" --include=*.py .`
# in the real project and ADD every other name you find.
COMPAT_EXPORTS = ["app", "get_local_ip"]

# Calls that run at import time and whose ORDER must never change.
SIDE_EFFECT_CALLS = [
    "ensure_dirs",
    "storage.ensure_root",
    "init_file_monitor",
    "file_monitor.add_change_callback",
    "file_monitor.add_activity_callback",
    "search_index_manager.start_crawler",
    "version_history.init",
    "initialize_cleanup",
]

# Names defined in the old top of app.py that later phases/app.py use. core.py must expose all of them
# (computed by AST: every phase's references into the Phase-1 region).
CORE_EXPORTS = [
    "RateLimiter",
    "_REVOKE_CODE_TTL",
    "_SHARE_UNLOCK_MAX_AGE",
    "_check_revoke_all_code",
    "_issue_revoke_all_code",
    "_request_is_secure",
    "_share_unlock_signer",
    "_stream_from_thread",
    "_trigger_reconcile",
    "app",
    "app_logger",
    "assembly_queue",
    "bulk_zip_cancelled",
    "bulk_zip_progress",
    "chunk_tracker",
    "csrf",
    "file_monitor",
    "generate_csrf",
    "get_local_ip",
    "get_protected_files",
    "login_required",
    "rate_limiter",
]

PHASES = {
    0: {
        "title": "Baseline, documentation and test harness (no code moved)",
        "version": "4.68",
        "modules": [],
        "routes": [],
        "symbols": [],
        "keep_in_app": [],
        "depends": [],
        "test": "test_phase00_baseline.py",
        "scope": "CLAUDE.md map + tests/refactor/* + baseline_routes.json. app.py untouched.",
    },
    1: {
        "title": "core.py + middleware.py (shared objects, hooks, startup side effects)",
        "version": "4.69",
        "modules": ["core.py", "middleware.py"],
        "routes": ["_cors_preflight"],
        "symbols": [
            "AssemblyJob",
            "AssemblyQueue",
            "CSRFProtect",
            "ChunkTracker",
            "RateLimiter",
            "SESSION_SECRET",
            "SLOW_REQUEST_THRESHOLD_SECONDS",
            "_AUX_PROC",
            "_CORS_ORIGIN_PATTERNS",
            "_CORS_ORIGIN_REGEXES",
            "_CSRF_HEADER_NAMES",
            "_CSRF_SAFE_METHODS",
            "_DynamicSecureSessionInterface",
            "_INLINE_STYLE_ELEMENT_HASHES",
            "_INLINE_STYLE_HASHES",
            "_PUBLIC_DOMAIN",
            "_REVOKE_CODE_TTL",
            "_SHARE_UNLOCK_MAX_AGE",
            "_apply_cors_headers",
            "_check_revoke_all_code",
            "_cors_origin_allowed",
            "_cors_preflight",
            "_issue_revoke_all_code",
            "_lean_redirect",
            "_log_request_duration",
            "_reconcile_gate",
            "_reconcile_rerun",
            "_reconcile_running",
            "_request_is_secure",
            "_request_via_trusted_tls",
            "_revoke_all_codes",
            "_revoke_all_codes_lock",
            "_share_unlock_signer",
            "_start_request_timer",
            "_stream_from_thread",
            "_trigger_reconcile",
            "_unauthenticated_response",
            "_wants_json_auth_error",
            "after_request",
            "app",
            "app_logger",
            "assembly_queue",
            "before_request",
            "bulk_zip_cancelled",
            "bulk_zip_progress",
            "chunk_tracker",
            "cleanup_stale_chunks_on_request",
            "csrf",
            "file_monitor",
            "generate_csrf",
            "get_client_ip",
            "get_local_ip",
            "get_protected_files",
            "internal_error",
            "login_required",
            "not_found",
            "rate_limiter",
            "request_logger",
            "secrets_compare",
            "timestamp_to_date_filter",
            "too_large",
            "validate_session",
        ],
        "keep_in_app": [],
        "depends": [],
        "test": "test_phase01_core_middleware.py",
        "scope": "Everything that is not a route in the old top 1,900 lines of app.py: app/Quart "
        "object, CSP/CORS/CSRF/session, rate limiter, ChunkTracker, AssemblyQueue, "
        "login_required, reconcile helpers, file_monitor init, startup side effects; ALL "
        "before_request/after_request/errorhandler/template_filter hooks (middleware.py, "
        "same order); the CORS OPTIONS route.",
    },
    2: {
        "title": "HLS video streaming -> routes/hls.py",
        "version": "4.70",
        "modules": ["routes/hls.py"],
        "routes": ["hls_start", "hls_status_route", "hls_files"],
        "symbols": [
            "_HLS_BASE_PROFILES",
            "_HLS_HFR_PROFILES",
            "_HLS_SEG_DURATION",
            "_SUBPROCESS_FLAGS",
            "_VIDEO_EXTS_HLS",
            "_extract_subtitles",
            "_ffmpeg_available",
            "_fix_fmp4_init_uris",
            "_hls_cache_key",
            "_hls_cache_root",
            "_hls_output_dir",
            "_hls_read_status",
            "_hls_status_lock",
            "_hls_write_status",
            "_patch_master_m3u8_subtitles",
            "_probe_streams",
            "_probe_video",
            "_resolve_ffmpeg",
            "_run_hls_transcode",
            "hls_files",
            "hls_start",
            "hls_status_route",
        ],
        "keep_in_app": [],
        "depends": [1],
        "test": "test_phase02_hls.py",
        "scope": "/hls_start, /hls_status, /hls_files + ffmpeg probing/transcoding helpers, HLS "
        "constants and locks.",
    },
    3: {
        "title": "Image preview/conversion -> routes/image_preview.py",
        "version": "4.71",
        "modules": ["routes/image_preview.py"],
        "routes": ["image_preview", "image_preview_status", "image_info"],
        "symbols": [
            "_ALL_IMG_EXTS",
            "_IMG_CACHE_THRESHOLD",
            "_IMG_NATIVE",
            "_IMG_NON_NATIVE",
            "_convert_to_webp",
            "_img_cache_key",
            "_img_cache_root",
            "_img_cached_path",
            "_img_cached_path_jpg",
            "_img_cached_path_png",
            "_img_conv_events",
            "_img_events_mutex",
            "_img_find_cached",
            "_img_meta_path",
            "_img_read_meta",
            "_img_status_lock",
            "_img_write_meta",
            "_pyvips_available",
            "_run_img_conversion",
            "image_info",
            "image_preview",
            "image_preview_status",
        ],
        "keep_in_app": [],
        "depends": [1],
        "test": "test_phase03_image_preview.py",
        "scope": "/image_preview, /image_preview_status, /image_info + pyvips/WebP conversion "
        "helpers, image cache constants and locks.",
    },
    4: {
        "title": "Version History routes -> routes/versions.py",
        "version": "4.72",
        "modules": ["routes/versions.py"],
        "routes": [
            "api_versions_list",
            "api_versions_restore",
            "api_versions_download",
            "download_recovered",
            "api_versions_retry",
            "api_versions_clear_failed",
            "api_versions_delete",
        ],
        "symbols": [
            "api_versions_clear_failed",
            "api_versions_delete",
            "api_versions_download",
            "api_versions_list",
            "api_versions_restore",
            "api_versions_retry",
            "download_recovered",
        ],
        "keep_in_app": [],
        "depends": [1],
        "test": "test_phase04_versions.py",
        "scope": "/api/versions/* (7 routes incl. /download/recovered): thin wrappers over "
        "version_history.py.",
    },
    5: {
        "title": "Office + archive preview -> routes/previews.py",
        "version": "4.73",
        "modules": ["routes/previews.py"],
        "routes": ["office_preview", "archive_preview"],
        "symbols": [
            "_archive_preview_sync",
            "_office_preview_sync",
            "archive_preview",
            "office_preview",
        ],
        "keep_in_app": [],
        "depends": [1],
        "test": "test_phase05_previews.py",
        "scope": "/office_preview, /archive_preview and their *_sync helpers.",
    },
    6: {
        "title": "Stats / SSE / health / search / speedtest / admin cache -> routes/stats.py + "
        "routes/admin.py",
        "version": "4.74",
        "modules": ["routes/stats.py", "routes/admin.py"],
        "routes": [
            "clear_media_preview",
            "admin_rebuild_cache",
            "admin_rebuild_cache_status",
            "storage_stats_api",
            "storage_stats_slow_api",
            "storage_stats_debug",
            "storage_stats_stream",
            "storage_stats_poll",
            "monitoring_status",
            "disk_stats_fast",
            "health_check",
            "search_files",
            "speedtest_ping",
            "speedtest_upload",
            "speedtest_download",
        ],
        "symbols": [
            "_LOOP_STALL_SECS",
            "_clear_media_preview_sync",
            "_loop_beat",
            "_loop_heartbeat",
            "_loop_watchdog_thread",
            "_loop_wd_started",
            "_rebuild_cache_worker",
            "_rebuild_state",
            "_rebuild_state_lock",
            "_start_loop_watchdog",
            "admin_rebuild_cache",
            "admin_rebuild_cache_status",
            "clear_media_preview",
            "disk_stats_fast",
            "health_check",
            "monitoring_status",
            "search_files",
            "speedtest_download",
            "speedtest_ping",
            "speedtest_upload",
            "storage_stats_api",
            "storage_stats_debug",
            "storage_stats_poll",
            "storage_stats_slow_api",
            "storage_stats_stream",
        ],
        "keep_in_app": [],
        "depends": [1, 2, 3],
        "test": "test_phase06_stats_admin.py",
        "scope": "storage stats (+SSE, polling), monitoring, disk, health_check, event-loop watchdog "
        "(before_serving), /api/search, speedtest -> stats.py; "
        "/admin/rebuild_cache(+status), /admin/clear_media_preview -> admin.py. Imports "
        "HLS/image cache helpers from routes.hls / routes.image_preview.",
    },
    7: {
        "title": "Share links (owner API, public /shared/*, admin) -> routes/shares.py",
        "version": "4.75",
        "modules": ["routes/shares.py"],
        "routes": [
            "create_share",
            "update_share_settings",
            "revoke_share",
            "share_status",
            "bulk_share",
            "shared_download",
            "shared_verify_passkey",
            "shared_request_access",
            "shared_request_status",
            "shared_file_download",
            "shared_browse",
            "shared_download_item",
            "shared_zip_selected",
            "admin_shares_count",
            "admin_shares_list",
            "admin_shares_pending_requests",
            "admin_shares_requests_stream",
            "admin_approve_share_request",
            "admin_deny_share_request",
            "admin_revoke_all_shares_code",
            "admin_revoke_all_shares",
        ],
        "symbols": [
            "_approval_cookie_name",
            "_dir_size",
            "_extract_security_fields",
            "_generate_passkey",
            "_get_live_share",
            "_human_size",
            "_is_passkey_unlocked",
            "_passkey_cookie_name",
            "_prune_expired_shares",
            "_resolve_shared_subpath",
            "_share_is_expired",
            "_shared_access_granted",
            "_stream_folder_zip",
            "admin_approve_share_request",
            "admin_deny_share_request",
            "admin_revoke_all_shares",
            "admin_revoke_all_shares_code",
            "admin_shares_count",
            "admin_shares_list",
            "admin_shares_pending_requests",
            "admin_shares_requests_stream",
            "bulk_share",
            "create_share",
            "revoke_share",
            "share_status",
            "shared_browse",
            "shared_download",
            "shared_download_item",
            "shared_file_download",
            "shared_request_access",
            "shared_request_status",
            "shared_verify_passkey",
            "shared_zip_selected",
            "update_share_settings",
        ],
        "keep_in_app": [],
        "depends": [1],
        "test": "test_phase07_shares.py",
        "scope": "/api/share*, /api/unshare, /shared/<token>/*, /admin/shares*, revoke-all codes. "
        "CSRF-exempt endpoints live here: keep @csrf.exempt exactly.",
    },
    8: {
        "title": "Uploads, chunks, assembly, cleanup schedulers -> routes/uploads.py",
        "version": "4.76",
        "modules": ["routes/uploads.py"],
        "routes": [
            "upload",
            "cleanup_chunks",
            "cancel_upload",
            "admin_cleanup_chunks",
            "chunk_stats",
            "upload_status",
            "get_assembly_status",
            "protect_assembly_job",
            "get_single_assembly_status",
        ],
        "symbols": [
            "admin_cleanup_chunks",
            "assembly_worker",
            "cancel_upload",
            "chunk_stats",
            "cleanup_chunks",
            "detect_ready_assemblies",
            "get_assembly_status",
            "get_single_assembly_status",
            "protect_assembly_job",
            "start_assembly_worker",
            "start_enhanced_cleanup_scheduler",
            "start_expired_share_cleanup_scheduler",
            "start_orphan_cleanup_scheduler",
            "upload",
            "upload_status",
        ],
        "keep_in_app": [],
        "depends": [1, 7],
        "test": "test_phase08_uploads.py",
        "scope": "/upload, /cleanup_chunks, /cancel_upload, /admin/cleanup_chunks, "
        "/admin/chunk_stats, /admin/upload_status, /api/assembly_status*, "
        "/api/protect_assembly; cleanup schedulers, assembly worker, "
        "detect_ready_assemblies. Imports _prune_expired_shares from routes.shares (so Phase "
        "7 must be done first).",
    },
    9: {
        "title": "Browse, download, file operations, bulk jobs -> routes/files.py",
        "version": "4.77",
        "modules": ["routes/files.py"],
        "routes": [
            "cancel_bulk_zip",
            "index",
            "download",
            "view_file",
            "bulk_download",
            "dir_info",
            "api_files",
            "bulk_move",
            "bulk_copy",
            "bulk_job_status",
            "bulk_delete",
            "rename_item",
            "mkdir",
            "delete",
            "api_check_conflicts",
            "api_exists",
        ],
        "symbols": [
            "_BULK_JOB_KEEP_SECS",
            "_bulk_copy_worker",
            "_bulk_find_free_name",
            "_bulk_job_start",
            "_bulk_jobs",
            "_bulk_jobs_lock",
            "_bulk_move_worker",
            "_bulk_start",
            "api_check_conflicts",
            "api_exists",
            "api_files",
            "bulk_copy",
            "bulk_delete",
            "bulk_download",
            "bulk_job_status",
            "bulk_move",
            "cancel_bulk_zip",
            "delete",
            "dir_info",
            "download",
            "index",
            "mkdir",
            "rename_item",
            "view_file",
        ],
        "keep_in_app": [],
        "depends": [1],
        "test": "test_phase09_files.py",
        "scope": "/, /<path>, /download, /view, /bulk-download, /cancel_bulk_zip, /api/files, "
        "/api/dir_info, /bulk_move|copy|job|delete, /rename, /mkdir, /delete, "
        "/api/check_conflicts, /api/exists.",
    },
    10: {
        "title": "Login/session pages + site meta -> routes/login.py + routes/site_meta.py; app.py "
        "becomes thin",
        "version": "4.78",
        "modules": ["routes/login.py", "routes/site_meta.py"],
        "routes": [
            "get_csrf_token",
            "robots_txt",
            "security_txt",
            "sitemap_xml",
            "check_session",
            "_debug_headers",
            "login",
            "logout",
        ],
        "symbols": [
            "_debug_headers",
            "check_session",
            "get_csrf_token",
            "login",
            "logout",
            "robots_txt",
            "security_txt",
            "sitemap_xml",
        ],
        "keep_in_app": [],
        "depends": [1],
        "test": "test_phase10_login_final.py",
        "scope": "/login, /logout, /check_session, /csrf-token -> login.py; /robots.txt, "
        "/sitemap.xml, /.well-known/security.txt, /debug/headers -> site_meta.py. app.py "
        "keeps only the imports, initialize_cleanup() and the __main__ block.",
    },
}
